travis:
  secure:
    BINSTAR_TOKEN: OGlpT+Z3vgfpdsrlRq2Dr7bhdSvbXfnD9JigpWQnhBMtQxac8mM0tBC9999Js2x/NnspXyrbscVt5ym31k1JqUOYTBuqMzPyhUDJFSplsvKQouADR5L/vHY6sBQ7xhaVnE/QexFz0ymbCl7ybf44UlHrJTbyHQ8cxsa6NgcLPZVLRvNrgKOWcyK2Ft8pqiIawBlzAs7AEF1y6cmyDA5MP0YE282XgEUP3PoZpRych0IVrH3o1LrIsN2T/909yYZYRDkM7HaieSz4GLjsvH4l3f6fB4NnvR2IkvM1iPHQ0xi66sVYOgaC5Cmh6leBPKrNq/yaOjnN352Whp+5tIzOrzNXajbDo0wqg6M2f10KWNzjWZiGiYDpcpGGwCx4s570xmvwyVpccyPM1lAYBclIG+Gne9Xq1j840EWwCqsQ8zbRERA3eY04y7mJRoabFNS7kv8l64oTDj/zOspPyOTqScUiGrwzgfDjHodTDJdz3w71aTCCcwWU/gOl5nqZYjNVtlb2+y9GpKein8V2uyvf5NLo5Zx+iLJGtmQxmqCmIR7MY35vAXs1WQDKnBPBSQuNcEb3XckkOKV/jtfXZ5u/frOuAKQ06+LkFJUScy2NUDyIu230YGMZI09R3PkE5Ni0V5eAxc5TZxGOaKGSZJHolfpPqrtS9paLMaTsP9zNMm4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
